name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      # Instalar Node.js e npm sem sudo usando NVM
      - name: Install Node.js and npm on the server
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa aluno@201.23.3.86 << 'EOF'
            # Baixar e instalar NVM (Node Version Manager)
            export NVM_DIR="$HOME/.nvm"
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash

            # Carregar o NVM e instalar Node.js
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # Carregar NVM
            nvm install 16  # Instalar Node.js 16.x
            nvm use 16      # Usar a versão instalada

            # Verificar as versões do Node.js e npm
            node -v
            npm -v
          EOF

      # Instalar PM2 no servidor
      - name: Install PM2 on the server
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa aluno@201.23.3.86 << 'EOF'
            npm install -g pm2
          EOF

      # Realizar o deploy
      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa aluno@201.23.3.86 << 'EOF'
            mkdir -p /home/aluno/projetos/api-airlytics
            cd /home/aluno/projetos/api-airlytics

            # Clonar ou atualizar o repositório
            if [ ! -d ".git" ]; then
              git clone https://github.com/cristianfatec/API-Airlytics.git .
            else
              git pull origin main
            fi

            # Instalar dependências
            npm install

            # Iniciar/atualizar o app com PM2
            pm2 restart app || pm2 start app.js
          EOF
        env:
          PORT: 8086
