name: Deploy to Server

on:
  push:
    branches:
      - main  # O deploy será feito ao fazer push na branch main (ou ajuste para sua branch)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checa o código do repositório
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Configura a chave SSH para acessar o servidor
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      # 3. Instalar PM2 no servidor (se necessário)
      - name: Install PM2 on the server
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa aluno@201.23.3.86 << 'EOF'
            npm install -g pm2
          EOF

      # 4. Conectar ao servidor remoto, configurar diretório e realizar deploy
      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa aluno@201.23.3.86 << 'EOF'
            # Criar o diretório se não existir e entrar nele
            mkdir -p /home/aluno/projetos/api-airlytics
            cd /home/aluno/projetos/api-airlytics

            # Clonar o repositório no servidor, se não estiver clonado ainda
            if [ ! -d ".git" ]; then
              git clone https://github.com/cristianfatec/API-Airlytics.git .
            else
              git pull origin main  # Atualizar o código se o repositório já estiver clonado
            fi

            # Instalar dependências
            npm install

            # Reiniciar a aplicação (se estiver usando o PM2)
            pm2 restart app || pm2 start app.js  # Ajuste o nome do arquivo principal
          EOF
        env:
          PORT: 8086  # Defina outras variáveis de ambiente necessárias
