name: Deploy to Server

on:
  push:
    branches:
      - main  # Defina o nome da sua branch de deploy, pode ser 'main' ou 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checa o código do repositório
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Configura a chave SSH para acessar o servidor
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      # 3. Instala as dependências do projeto
      - name: Install dependencies
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa aluno@201.23.3.86 << 'EOF'
            cd /home/aluno/projetos/api-airlytics  # Certifique-se de substituir pelo caminho correto
            npm install
          EOF

      # 4. Faz o deploy para o servidor remoto
      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa aluno@201.23.3.86 << 'EOF'
            cd /home/aluno/projetos/api-airlytics  # Certifique-se de substituir pelo caminho correto
            git pull origin main
            npm install
            pm2 restart app  # Ou outro comando para reiniciar seu servidor
          EOF
        env:
          MONGODB_URI: 'mongodb+srv://cristianfatec:123Fatec@apiairlytics.1znrl.mongodb.net/?retryWrites=true&w=majority&appName=apiAirlytics'
          PORT: 8086
