name: Docker CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Check Docker version
        run: docker --version

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t your-dockerhub-username/your-image-name:latest .

      - name: Push Docker image to DockerHub
        run: docker push your-dockerhub-username/your-image-name:latest

      - name: SSH and Deploy to Server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: 201.23.3.86
          username: aluno
          key: ${{ secrets.SSH_KEY }}
          port: 22

          script: |
            docker pull your-dockerhub-username/your-image-name:latest
            docker stop app-container || true
            docker rm app-container || true
            docker run -d -p 8086:3000 --name app-container your-dockerhub-username/your-image-name:latest
