name: Deploy to Server

on:
  push:
    branches:
      - main  # Defina o nome da sua branch de deploy, pode ser 'main' ou 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checa o código do repositório
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Configura a chave SSH para acessar o servidor
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      # 3. Instala o Node.js e PM2 no servidor remoto
      - name: Install Node.js and PM2 on the remote server
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa aluno@201.23.3.86 << 'EOF'
            # Atualiza os pacotes do servidor
            sudo apt update -y
            sudo apt upgrade -y

            # Instala o Node.js (substitua pela versão desejada)
            curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
            sudo apt install -y nodejs

            # Instala o PM2 globalmente
            sudo npm install -g pm2
          EOF

      # 4. Instala as dependências do projeto
      - name: Install dependencies
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa aluno@201.23.3.86 << 'EOF'
            cd /home/aluno/projetos/api-airlytics  # Substitua com o caminho correto
            npm install
          EOF

      # 5. Faz o deploy para o servidor remoto
      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa aluno@201.23.3.86 << 'EOF'
            cd /home/aluno/projetos/api-airlytics  # Substitua com o caminho correto
            git pull origin main
            npm install
            pm2 restart app  # Ou outro comando para reiniciar seu servidor
          EOF
        env:
          MONGODB_URI: 'mongodb+srv://cristianfatec:123Fatec@apiairlytics.1znrl.mongodb.net/?retryWrites=true&w=majority&appName=apiAirlytics'
          PORT: 8086
